const data = [
    {
        id:2,
        pid:0,
        path:'/course',
        name:'Course',
        title:'课程管理0'
    },
    {
        id:3,
        pid:2,
        path:'/course',
        name:'Course',
        title:'课程管理2'
    },
    {
        id:10,
        pid:0,
        path:'/class',
        name:'Course',
        title:'教室'
    },
    {
        id:4,
        pid:4,
        path:'/course',
        name:'Course',
        title:'课程管理2'
    },
    {
        id:4,
        pid:3,
        path:'/course',
        name:'Course',
        title:'课程管理2'
    },
    {
        id:5,
        pid:0,
        path:'/student',
        name:'Course',
        title:'学生管理'
    },
    {
        id:6,
        pid:5,
        path:'/course',
        name:'Course',
        title:'学生管理孩子'
    },
    {
        id:7,
        pid:5,
        path:'/course',
        name:'Course',
        title:'学生管理孩子'
    },
    {
        id:21,
        pid:10,
        path:'/course',
        name:'Course',
        title:'学生管理孩子'
    },
    {
        id:22,
        pid:21,
        path:'/course',
        name:'Course',
        title:'学生管理孩子'
    },

]